services:
  api-qr:
    build: ./api-qr
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy   # espera a que Postgres acepte conexiones
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/qr_duoc

  api-ubicacion:
    build: ./api-ubicacion
    ports:
      - "8002:8002"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/qr_duoc

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qr_duoc
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d qr_duoc"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
